# Calling Peaks with ArchR

```{r, include=FALSE, eval=FALSE}
setwd("/Volumes/JG_SSD_2/ArchR_Walkthrough/")
#load("Save-ArchR-Walkthrough-Chapter1-Feb13.Rdata")
save.image("Save-ArchR-Walkthrough-Feb17-0254.Rdata")
```

## Calling Peaks w/ Macs2

We can now save our original projHeme3 using `saveArchRProject` from ArchR.

```{r eval=FALSE}
saveArchRProject(projHeme3)
```

```{r eval=FALSE}
#Create Group Coverage Files that can be used for downstream analysis (~5-10 minutes)
projHeme4 <- addGroupCoverages(ArchRProj = projHeme3, groupBy = "Clusters")

#Find Path to Macs2 binary. This function sometimes struggles if you are using conda environment
#for installation of python packages. If this function fails try providing a direct path manually
pathToMacs2 <- findMacs2()

#Call Reproducible Peaks w/ Macs2 (~5-10 minutes)
projHeme4 <- addReproduciblePeakSet(
	ArchRProj = projHeme4, 
	groupBy = "Clusters", 
	pathToMacs2 = pathToMacs2
)

getPeakSet(projHeme4)
# GRanges object with 158378 ranges and 12 metadata columns:
#             seqnames              ranges strand |     score
#                <Rle>           <IRanges>  <Rle> | <numeric>
#   Cluster10     chr1       752327-752827      * |   2.74288
#    Cluster9     chr1       760866-761366      * |   2.65888
#    Cluster2     chr1       762700-763200      * |   18.7147
#    Cluster2     chr1       779639-780139      * |   2.81931
#    Cluster8     chr1       793519-794019      * |   3.74498
#         ...      ...                 ...    ... .       ...
#    Cluster5     chrX 154841853-154842353      * |   3.43901
#   Cluster12     chrX 154842354-154842854      * |   7.60796
#    Cluster4     chrX 154862032-154862532      * |   9.27826
#    Cluster5     chrX 154912371-154912871      * |   6.27394
#    Cluster6     chrX 154996898-154997398      * |   2.65432
```

## Calling Peaks w/ TileMatrix

```{r eval=FALSE}
#Call Reproducible Peaks w/ TileMatrix (~2 minutes)
projHemeTmp <- addReproduciblePeakSet(
	ArchRProj = projHeme4, 
	groupBy = "Clusters",
	peakMethod = "Tiles",
	method = "p"
)

getPeakSet(projHemeTmp)
# GRanges object with 277187 ranges and 9 metadata columns:
#            seqnames              ranges strand |   mlog10p     Group
#               <Rle>           <IRanges>  <Rle> | <numeric>     <Rle>
#        [1]     chr1       752000-752499      * |     1.682 Cluster10
#        [2]     chr1       752500-752999      * |     4.952 Cluster10
#        [3]     chr1       758500-758999      * |     1.037  Cluster4
#        [4]     chr1       761000-761499      * |     2.204  Cluster9
#        [5]     chr1       762000-762499      * |     3.246  Cluster4
#        ...      ...                 ...    ... .       ...       ...
#   [277183]     chrX 154842000-154842499      * |     8.936 Cluster12
#   [277184]     chrX 154842500-154842999      * |    12.546 Cluster12
#   [277185]     chrX 154862000-154862499      * |     2.449  Cluster4
#   [277186]     chrX 154912500-154912999      * |     2.484  Cluster5
#   [277187]     chrX 154997000-154997499      * |     4.236  Cluster8
```

Lets see how well this compares to Macs2

```{r eval=FALSE}
#Peak Overlap
length(subsetByOverlaps(getPeakSet(projHeme4), getPeakSet(projHemeTmp))) / length(getPeakSet(projHeme4))
# 0.9681079
length(subsetByOverlaps(getPeakSet(projHemeTmp), getPeakSet(projHeme4))) / length(getPeakSet(projHemeTmp))
# 0.7902066

#Extend to 1kb
length(subsetByOverlaps(resize(getPeakSet(projHeme4), 1000, "center"), getPeakSet(projHemeTmp))) / length(getPeakSet(projHeme4))
# 0.9750028
length(subsetByOverlaps(getPeakSet(projHemeTmp), resize(getPeakSet(projHeme4), 1000, "center"))) / length(getPeakSet(projHemeTmp))
# 0.858287
```

## Add Peak Matrix

We can now save our original projHeme4 using `saveArchRProject` from ArchR.

```{r eval=FALSE}
saveArchRProject(projHeme4)
```


```{r eval=FALSE}
getPeakSet(projHeme4)
# GRanges object with 158378 ranges and 12 metadata columns:
#             seqnames              ranges strand |     score
#                <Rle>           <IRanges>  <Rle> | <numeric>
#   Cluster10     chr1       752327-752827      * |   2.74288
#    Cluster9     chr1       760866-761366      * |   2.65888
#    Cluster2     chr1       762700-763200      * |   18.7147
#    Cluster2     chr1       779639-780139      * |   2.81931
#    Cluster8     chr1       793519-794019      * |   3.74498
#         ...      ...                 ...    ... .       ...
#    Cluster5     chrX 154841853-154842353      * |   3.43901
#   Cluster12     chrX 154842354-154842854      * |   7.60796
#    Cluster4     chrX 154862032-154862532      * |   9.27826
#    Cluster5     chrX 154912371-154912871      * |   6.27394
#    Cluster6     chrX 154996898-154997398      * |   2.65432

#~1-2 Minutes
projHeme5 <- addPeakMatrix(projHeme4)

getAvailableMatrices(projHeme5)
# [1] "GeneIntegrationMatrix" "GeneScoreMatrix"       "PeakMatrix"           
# [4] "TileMatrix" 
```








