---
output:
  html_document:
    theme: yeti  # many options for theme, this one is my favorite.
params:
  threads: 20
  rdata: ""
  token: ""
  ref: ""
  out: ""
editor_options: 
  markdown: 
    wrap: 72
---

# Manage ArchR's Dependencies

We recommend installing ArchR using [renv](https://rstudio.github.io/renv/index.html), a tool for dependency management that will make it easier for you to get going with analysis without having to worry about package installation and versions issues. We also provide a Docker container, which together with renv, helps maintain reproducible environments so you can share your results with collaborators. 


## Start Container Locally

1.  Install `renv` 
    `install.packages("renv")`

2.  Install Docker [Instructions](https://docs.docker.com/get-started/)
    for mac, linux, or windows.

3.  Start up the Docker engine by opening your Docker Desktop
    application.

4.  If you have fragment/BAM files on local, `cd` into that directory.

Follow track one or two depending on whether or not you want to leverage
the `renv` global cache:

**TRACK ONE:** Spin up container with R packages pre-baked.

1.  Pull Docker image from Dockerhub:
    `docker pull corceslab/archr:baked`

1.  Either `cd` into that directory or define a variable for the path to
    the directory with all your data: `MY_DATA_PATH="path/to/data"`
    
    $\mathrm{N}\!\!\mathrm{B}$: If you do the latter you must change the
    command to run the Docker image.

1.  Run container, mounting a volume into the directory with all your
    data

<!-- -->

    docker run \
    -e PASSWORD=yourpassword \
    -e ROOT=TRUE \
    -e USERID=$UID \
    -v $(pwd):/home/rstudio/myproject/ \
    -p 14618:8787 \
    corceslab/archr:baked

1.  On the Docker Desktop GUI click on the icon for "Open in Browser."
    Or head to `localhost:14618/` on your browser

1.  Run `renv::init()`

1.  Wait for `renv` to install your project library. Output should be:

<!-- -->

        * Restoring project ...
        The following package(s) will be updated:

Followed by a list of ArchR's dependencies.

You may also see:

    This project already has a lockfile. What would you like to do?
    1: Restore the project from the lockfile.
    2: Discard the lockfile and re-initialize the project.
    3: Activate the project without snapshotting or installing any packages.
    4: Abort project initialization.

In this case, write 1.

**TRACK TWO:** Spin up container leveraging the `renv` global cache:

1.  Pull Docker image from Dockerhub:

`Docker pull corceslab/archr:usecache`

1.  Find the location of the `renv` cache in your local machine:

In R: `renv:::renv_paths_cache()`

1.  Either `cd` into that directory or define a variable for the path to
    the directory with all your data: `MY_DATA_PATH="path/to/data"` If
    you do the latter you must change the command to run the Docker
    image.

1.  On your terminal, define a variable for the path of the `renv` cache
    on your local machine:
    `RENV_PATHS_CACHE_HOST="~/Library/Caches/org.R-project.R/R/renv"`

1.  Define a variable for the path where you want to mount the `renv`
    cache inside the container:
    `RENV_PATHS_CACHE_CONTAINER="/home/rstudio/myproject/"`

1.  Run container, with two mounts: One into the directory with all your
    data and another for the `renv` cache.

<!-- -->

    docker run \
    -e PASSWORD=yourpassword \
    -e ROOT=TRUE \
    -e USERID=$UID \
    -e "${RENV_PATHS_CACHE_HOST}:${RENV_PATHS_CACHE_CONTAINER}" \
    -v $(pwd):/home/rstudio/myproject/ \
    -p 14618:8787 \
    corceslab/archr:usecache 

1.  On the Docker Desktop GUI click on the icon for "Open in Browser" OR
    head to `localhost:14618/` on your browser
2.  Run `renv::restore()`

Output should be:

    * Restoring project ...
    The following package(s) will be updated:

Followed by a list of ArchR's dependencies. 
$\mathrm{N}\!\!\mathrm{B}$: If you get warning: "The project may be out of sync -- use
`renv::status()` for more details." Please disregard.

1.  Wait for `renv` to install your project library. If you are running
    on a slow internet connection, set options(timeout = 800).

# Renv solo locally

1.  `cd` into the directory where you have your data

2.  Run
    `wget -O renv.lock "https://raw.githubusercontent.com/rcorces/ArchR_docker/main/renv.lock?token=AOHUDISVOOHAHDXW7AJBJFLB3XHEM"`

3.  Install `renv` in R

`install.packages('renv')`

1.  Check your working directory in R.

Use `getwd()`

1.  Run `renv::init()`

1.  Wait for `renv` to install your project library. Output should be:
```
Restoring project ...
The following package(s) will be updated:
```
Followed by a list of ArchR's dependencies.
You may also see:
```
This project already has a lockfile. What would you like to do?
1: Restore the project from the lockfile.
2: Discard the lockfile and re-initialize the project.
3: Activate the project without snapshotting or installing any packages.
4: Abort project initialization.
```
In this case, write 1.

1.  Restart your R session. No need to save your workspace. If you are in RStudio: command/ctrl + shift + F10. You can also use `.rs.restartR().`

## General Notes on renv
* Full documentation on `renv` can be found [here] (https://rstudio.github.io/renv/articles/renv.html)
*If you install any additional packages that you would like to be available when you re-initialize a lock file, you can record these packages into the lockfile using the renv::snapshot() function. Run this function after new libraries have been installed and loaded. By default, renv::snapshot() will write to a lock file called renv.lock in the current working directory, though this can be changed using the lockfile parameter.
* If you are ever asked to upgrade packages, this might mess up the dependency system that ArchR relies on so you should avoid upgrading packages included in the lockfile at all costs. In general, anytime you install a new package, R will give you the option of upgrading existing packages that have newer versions. While using renv, you should always select “none” (option 3) to avoid unintentionally altering packages that are part of the expected renv environment.
* To deactivate renv pass your directory to:
`renv::deactivate(project = NULL)`

## General Notes on Docker

* Make sure to never mount host /, ~ or $HOME or any other root-level directory, like /opt, /etc, /usr, etc. This is because when you use -v flag, docker recursively sets root as a owner (equivalent of chmod -R u=rwx /host_dir_path) for all files and folders within mount point
* On Linux-based hosts, sharing volumes requires that the UID on the container match the UID on the host, otherwise any files edited or created in the container will be owned by root instead. Check the user id on the host (id) and pass this value to the docker container as an environmental variable, -e USERID=\$UID, where \$UID is the local user id.
* If you are not familiar with CLI or prefer to use a more user-friendly interface, Docker Desktop provides functionality to pull images, run containers, and many other actions. 
* By default, any data created inside the container is only available from within the container and only while the container is running (that is, while the parent process of the container is running). 

